---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: code-server.pkg.maki.lol.0.0.1
spec:
  refName: code-server.pkg.maki.lol
  version: 0.0.1
  releaseNotes: |
    Initial release of code server
  valuesSchema:
    openAPIv3:
      title: code-server.pkg.maki.lol values schema
      examples:
      - namespace: coder
        suffix:
        code_server:
          external_url_format: https://code-server.{}.example.com
          storage_size: 30Gi
          create_namespace: true
          clean: true
      properties:
        namespace:
          type: string
          description: Namespace to install the code server
          default: demo
          examples:
          - developer-env
        suffix:
          type: string
          description: Suffix of the namespace
          default:
          examples:
          - dev1
          - dev2
        code_server:
          description: Code Server configuration
          type: object
          properties:
            external_url_format:
              type: string
              description: External URL format
              default: https://code-server-{}.localhost.ik.am
            storage_size:
              type: string
              description: Storage Size
              default: 10Gi
            create_namespace:
              type: boolean
              description: Whether to create the namespace
              default: true
            clean:
              type: boolean
              description: Whether to clean extension directory etc.
              default: false
            ingress_class:
              type: string
              description: Explicit Ingress class name
              default:
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/making/code-server-bundle
      template:
      - ytt: { }
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --diff-changes=true
          - --diff-mask=false
          inspect:
            rawOptions:
            - --tree=true