apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: code-server.pkg.maki.lol.0.0.11
spec:
  refName: code-server.pkg.maki.lol
  version: 0.0.11
  releaseNotes: |
    Initial release of code server
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: Namespace to install the code server
          default: demo
        suffix:
          type: string
          nullable: true
          description: Suffix of the namespace
          default: null
        code_server:
          type: object
          additionalProperties: false
          properties:
            external_url_format:
              type: string
              description: External URL format
              default: https://code-server-{}.localhost.ik.am
            storage_size:
              type: string
              description: Storage Size
              default: 10Gi
            create_namespace:
              type: boolean
              description: Whether to create the namespace
              default: true
            clean:
              type: boolean
              description: Whether to clean extension directory etc.
              default: false
            ingress_class:
              type: string
              nullable: true
              description: Explicit Ingress class name
              default: null
        resources:
          type: object
          additionalProperties: false
          properties:
            limits:
              type: object
              additionalProperties: false
              properties:
                cpu:
                  type: string
                  description: Limits describes the maximum amount of cpu resources allowed.
                  default: 2000m
                memory:
                  type: string
                  description: Limits describes the maximum amount of memory resources allowed.
                  default: 4Gi
            requests:
              type: object
              additionalProperties: false
              properties:
                cpu:
                  type: string
                  description: Requests describes the minimum amount of cpu resources required.
                  default: 1000m
                memory:
                  type: string
                  description: Requests describes the minimum amount of memory resources required.
                  default: 2Gi
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/making/code-server-bundle:0.0.11
      template:
      - ytt: {}
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --diff-changes=true
          - --diff-mask=false
          inspect:
            rawOptions:
            - --tree=true
