apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: code-server.pkg.maki.lol.0.1.0
spec:
  refName: code-server.pkg.maki.lol
  version: 0.1.0
  releaseNotes: |
    Initial release of code server
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: Namespace to install the code server
          default: demo
        suffix:
          type: string
          nullable: true
          description: Suffix of the namespace
          default: null
        code_server:
          type: object
          additionalProperties: false
          properties:
            image:
              type: string
              nullable: true
              description: Image name to override the default code server image
              default: null
            image_pull_secrets:
              type: array
              description: Image pull secrets for code server
              items:
                nullable: true
                description: Image pull secret for code server
                default: {}
              default: []
            args:
              type: array
              nullable: true
              description: Extra args to the code server
              items:
                type: string
                default: ""
              default: null
            env:
              type: array
              description: Extra env to the code server
              items:
                nullable: true
                description: name and value of an environment variable
                default: {}
              default: []
            external_url_format:
              type: string
              description: External URL format
              default: https://code-server-{}.vcap.me
            storage_size:
              type: string
              description: Storage Size
              default: 10Gi
            create_namespace:
              type: boolean
              description: Whether to create the namespace
              default: true
            clean:
              type: boolean
              description: Whether to clean extension directory etc.
              default: false
            ingress_class:
              type: string
              nullable: true
              description: Explicit Ingress class name in annotations (deprecated in favor of code_server.ingress.class_name)
              default: null
            ingress:
              type: object
              additionalProperties: false
              properties:
                class_name:
                  type: string
                  nullable: true
                  description: Explicit Ingress class name in spec.ingressClassName
                  default: null
                annotations:
                  nullable: true
                  description: Additional annotations on the ingress resource
                  default: {}
                tls_disabled:
                  type: boolean
                  description: Whether to disable tls.
                  default: false
            clusterissuer:
              type: string
              nullable: true
              description: ClusterIssuer name to generate the code server's certificate
              default: null
            auth_disabled:
              type: boolean
              description: Whether to disable authentication.
              default: false
            init_script:
              type: string
              description: Additional script inside initContainer
              default: ""
        resources:
          type: object
          additionalProperties: false
          properties:
            limits:
              type: object
              additionalProperties: false
              properties:
                cpu:
                  type: string
                  description: Limits describes the maximum amount of cpu resources allowed.
                  default: 2000m
                memory:
                  type: string
                  description: Limits describes the maximum amount of memory resources allowed.
                  default: 4Gi
            requests:
              type: object
              additionalProperties: false
              properties:
                cpu:
                  type: string
                  description: Requests describes the minimum amount of cpu resources required.
                  default: 1000m
                memory:
                  type: string
                  description: Requests describes the minimum amount of memory resources required.
                  default: 2Gi
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/making/code-server-bundle:0.1.0
      template:
      - ytt: {}
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --diff-changes=true
          - --diff-mask=false
          inspect:
            rawOptions:
            - --tree=true
