#@data/values
#@overlay/match-child-defaults missing_ok=True
---
namespace: demo
suffix:
code_server:
  external_url_format: https://coder-server-{}.localhost.ik.am
  storage_size: 10Gi
  create_namespace: true
  clean: false
  ingress_class: 