#@data/values
#@overlay/match-child-defaults missing_ok=True
---
namespace: demo
suffix:
code_server:
  external_url_format: https://code-server-{}.localhost.ik.am
  storage_size: 10Gi
  create_namespace: true
  clean: false
  ingress_class:
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi