#@data/values-schema
---
#@schema/desc "Namespace to install the code server"
namespace: demo
#@schema/desc "Suffix of the namespace"
#@schema/nullable
suffix: ""
code_server:
  #@schema/desc "image name to override the default code server image"
  #@schema/nullable  
  image: ""
  #@schema/desc "extra args to the code server"
  #@schema/nullable
  args:
  - ""
  #@schema/desc "extra env to the code server"
  env:
  #@schema/desc "name and value of an environment variable"
  #@schema/type any=True
  - {}
  #@schema/desc "External URL format"
  external_url_format: https://code-server-{}.vcap.me
  #@schema/desc "Storage Size"
  storage_size: 10Gi
  #@schema/desc "Whether to create the namespace"
  create_namespace: true
  #@schema/desc "Whether to clean extension directory etc."
  clean: false
  #@schema/desc "Explicit Ingress class name in annotations (deprecated in favor of code_server.ingress.class_name)"
  #@schema/nullable
  ingress_class: ""
  ingress:
    #@schema/desc "Explicit Ingress class name in spec.ingressClassName"
    class_name: ""
    #@schema/desc "Additional annotations on the ingress resource"
    #@schema/type any=True
    annotations: {}
  #@schema/desc "ClusterIssuer name to generate the code server's certificate"
  #@schema/nullable
  clusterissuer: ""
  #@schema/desc "Whether to disable authentication."
  auth_disabled: false
  #@schema/desc "Whether to disable tls."
  tls_disabled: false
resources:
  limits:
    #@schema/desc "Limits describes the maximum amount of cpu resources allowed."
    cpu: 2000m
    #@schema/desc "Limits describes the maximum amount of memory resources allowed."
    memory: 4Gi
  requests:
    #@schema/desc "Requests describes the minimum amount of cpu resources required."
    cpu: 1000m
    #@schema/desc "Requests describes the minimum amount of memory resources required."
    memory: 2Gi