apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: code-server-demo2
  namespace: developer-env
spec:
  serviceAccountName: kapp-sa
  packageRef:
    refName: code-server.pkg.maki.lol
    versionSelection:
      constraints: 0.0.3
  values:
  - secretRef:
      name: developer-env-demo1-values
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-env-demo2-values
  namespace: developer-env
stringData:
  values.yaml: |
    ---
    namespace: developer-env
    suffix: demo2