apiVersion: v1
kind: Namespace
metadata:
  name: developer-env
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: developer-env
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kapp-role-binding
  namespace: developer-env
subjects:
- kind: ServiceAccount
  name: kapp-sa
  namespace: developer-env
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin